export const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST';
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_GET_FAIL = 'PRODUCTS_GET_FAIL';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';
